const GET_ALL_AUCTION_REQ = "GET_ALL_AUCTION_REQ";
const GET_ALL_AUCTION_SUCCESS = "GET_ALL_AUCTION_SUCCESS";
const GET_ALL_AUCTION_FAILED = "GET_ALL_AUCTION_FAILED";

export {GET_ALL_AUCTION_REQ, GET_ALL_AUCTION_SUCCESS, GET_ALL_AUCTION_FAILED}

