const GET_ALL_AUCTION_REQ = "GET_ALL_AUCTION_REQ";
const GET_ALL_AUCTION_SUCCESS = "GET_ALL_AUCTION_SUCCESS";
const GET_ALL_AUCTION_FAILED = "GET_ALL_AUCTION_FAILED";

const GET_ONE_AUCTION_REQ = "GET_ONE_AUCTION_REQ";
const GET_ONE_AUCTION_SUCCESS = "GET_ONE_AUCTION_SUCCESS";
const GET_ONE_AUCTION_FAILED = "GET_ONE_AUCTION_FAILED";
const AUCTION_CLEAR = "AUCTION_CLEAR";

export {
    GET_ALL_AUCTION_REQ, GET_ALL_AUCTION_SUCCESS, GET_ALL_AUCTION_FAILED,
    GET_ONE_AUCTION_REQ, GET_ONE_AUCTION_SUCCESS, GET_ONE_AUCTION_FAILED,AUCTION_CLEAR
}

