const ADD_TO_BASKET = "ADD_TO_BASKET";
const ADD_QUANTITY_TO_BASKET = "ADD_QUANTITY__TO_BASKET";
const REMOVE_FROM_BASKET = "REMOVE_FROM_BASKET";
const CLEAR_BASKET = "CLEAR_BASKET";


export { ADD_TO_BASKET, REMOVE_FROM_BASKET, ADD_QUANTITY_TO_BASKET, CLEAR_BASKET};