const FETCH_MY_AUCTIONS = "FETCH_MY_AUCTIONS";
const FETCH_MY_AUCTIONS_SUCCESS = "FETCH_MY_AUCTIONS_SUCCESS";
const FETCH_MY_AUCTIONS_FAIL = "FETCH_MY_AUCTIONS_FAIL";
const CREATE_AUCTION = "CREATE_AUCTION";
const CREATE_AUCTION_SUCCESS = "CREATE_AUCTION_SUCCESS";
const CREATE_AUCTION_FAIL = "CREATE_AUCTION_FAIL";

export { FETCH_MY_AUCTIONS, FETCH_MY_AUCTIONS_SUCCESS, FETCH_MY_AUCTIONS_FAIL, CREATE_AUCTION, CREATE_AUCTION_SUCCESS, CREATE_AUCTION_FAIL}