const SEND_ORDER = 'SEND_ORDER';
const SEND_ORDER_SUCCESS = 'SET_SENDED_ORDER';
const SEND_ORDER_FAIL = 'SEND_ORDER_FAIL';

const FETCH_ORDERS = 'FETCH_ORDERS';
const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';

export { SEND_ORDER, SEND_ORDER_SUCCESS, SEND_ORDER_FAIL, FETCH_ORDERS, FETCH_ORDERS_SUCCESS, FETCH_ORDERS_FAIL };