const PRODUCTS_REQ = "PRODUCTS_REQ";
const PRODUCTS_REQ_SUCCESS = "PRODUCTS_REQ_SUCCESS";
const PRODUCTS_REQ_FAIL = "PRODUCTS_REQ_FAIL";

const PRODUCT_REQ = "PRODUCT_REQ";
const PRODUCT_CLEAR = "PRODUCT_CLEAR";
const PRODUCT_REQ_SUCCESS = "PRODUCT_REQ_SUCCESS";
const PRODUCT_REQ_FAIL = "PRODUCT_REQ_FAIL";

export {PRODUCTS_REQ, PRODUCTS_REQ_SUCCESS, PRODUCTS_REQ_FAIL, PRODUCT_REQ, PRODUCT_REQ_SUCCESS, PRODUCT_REQ_FAIL, PRODUCT_CLEAR}

