const FETCH_PRODUCTS = "FETCH_PRODUCTS";
const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
const FETCH_PRODUCTS_FAIL = "FETCH_PRODUCTS_FAIL";
const CREATE_PRODUCT = "CREATE_PRODUCT";
const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
const CREATE_PRODUCT_FAIL = "CREATE_PRODUCT_FAIL";

export { FETCH_PRODUCTS, FETCH_PRODUCTS_SUCCESS, FETCH_PRODUCTS_FAIL, CREATE_PRODUCT, CREATE_PRODUCT_SUCCESS, CREATE_PRODUCT_FAIL}