const FETCH_PROFILE = "FETCH_PROFILE";
const FETCH_PROFILE_SUCCESS = "FETCH_PROFILE_SUCCESS";
const FETCH_PROFILE_FAIL = "FETCH_PROFILE_FAIL";

const UPDATE_PROFILE = "UPDATE_PROFILE";
const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";

const CLEAR_PROFILE_ERROR = 'CLEAR_PROFILE_ERROR'

export { FETCH_PROFILE, FETCH_PROFILE_SUCCESS, FETCH_PROFILE_FAIL, UPDATE_PROFILE, UPDATE_PROFILE_SUCCESS, UPDATE_PROFILE_FAIL, CLEAR_PROFILE_ERROR}