const FETCH_PROFILE = "FETCH_PROFILE";
const FETCH_PROFILE_SUCCESS = "FETCH_PROFILE_SUCCESS";
const FETCH_PROFILE_FAIL = "FETCH_PROFILE_FAIL";

export { FETCH_PROFILE, FETCH_PROFILE_SUCCESS, FETCH_PROFILE_FAIL}