const SIGN_UP_REQ = "SIGN_UP_REQ";
const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
const SIGN_UP_FAIL = "SIGN_UP_FAIL";
const LOG_IN_REQ = "LOG_IN_REQ";
const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
const LOG_IN_FAIL = "LOG_IN_FAIL";


export {SIGN_UP_REQ, SIGN_UP_SUCCESS, SIGN_UP_FAIL, LOG_IN_REQ, LOG_IN_SUCCESS,LOG_IN_FAIL}

